# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rets4r}
  s.version = "1.1.17"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Patterson", "John Wulff", "begetting", "Jacob Basham", "Joseph Holsten"]
  s.date = %q{2010-09-19}
  s.description = %q{RETS4R is a native Ruby interface to the RETS (Real Estate Transaction Standard). It currently is built for the 1.5 specification, but support for 1.7 and 2.0 are planned. It does not currently implement all of the specification, but the most commonly used portions. Specifically, there is no support for Update transactions.}
  s.email = ["scott.patterson@digitalaun.com", "john@johnwulff.com", "brian@terra-firma-design.com", "jacob@paperpigeons.net", "joseph@josephholsten.com"]
  s.extra_rdoc_files = [
    "CHANGELOG",
     "CONTRIBUTORS",
     "LICENSE",
     "MANIFEST",
     "NEWS",
     "README.rdoc",
     "RUBYS",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG",
     "CONTRIBUTORS",
     "Gemfile",
     "LICENSE",
     "MANIFEST",
     "NEWS",
     "README.rdoc",
     "RUBYS",
     "Rakefile",
     "TODO",
     "examples/client_get_object.rb",
     "examples/client_login.rb",
     "examples/client_mapper.rb",
     "examples/client_metadata.rb",
     "examples/client_parser.rb",
     "examples/client_search.rb",
     "examples/settings.yml",
     "lib/rets4r.rb",
     "lib/rets4r/auth.rb",
     "lib/rets4r/client.rb",
     "lib/rets4r/client/data.rb",
     "lib/rets4r/client/dataobject.rb",
     "lib/rets4r/client/exceptions.rb",
     "lib/rets4r/client/links.rb",
     "lib/rets4r/client/metadata.rb",
     "lib/rets4r/client/parsers/compact.rb",
     "lib/rets4r/client/parsers/compact_nokogiri.rb",
     "lib/rets4r/client/parsers/metadata.rb",
     "lib/rets4r/client/parsers/response_parser.rb",
     "lib/rets4r/client/requester.rb",
     "lib/rets4r/client/transaction.rb",
     "lib/rets4r/core_ext/array/extract_options.rb",
     "lib/rets4r/core_ext/class/attribute_accessors.rb",
     "lib/rets4r/core_ext/hash/keys.rb",
     "lib/rets4r/core_ext/hash/slice.rb",
     "lib/rets4r/listing_mapper.rb",
     "lib/rets4r/listing_service.rb",
     "lib/rets4r/loader.rb",
     "lib/tasks/annotations.rake",
     "lib/tasks/coverage.rake",
     "rets4r.gemspec",
     "spec/rets4r_compact_data_parser_spec.rb",
     "test/data/1.5/bad_compact.xml",
     "test/data/1.5/count_only_compact.xml",
     "test/data/1.5/error.xml",
     "test/data/1.5/invalid_compact.xml",
     "test/data/1.5/login.xml",
     "test/data/1.5/metadata.xml",
     "test/data/1.5/search_compact.xml",
     "test/data/1.5/search_compact_big.xml",
     "test/data/1.5/search_unescaped_compact.xml",
     "test/data/listing_service.yml",
     "test/test_auth.rb",
     "test/test_client.rb",
     "test/test_client_links.rb",
     "test/test_compact_nokogiri.rb",
     "test/test_helper.rb",
     "test/test_listing_mapper.rb",
     "test/test_loader.rb",
     "test/test_parser.rb",
     "test/test_quality.rb"
  ]
  s.homepage = %q{http://rets4r.rubyforge.org/}
  s.rdoc_options = ["--charset=UTF-8", "--charset=UTF-8", "--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rets4r}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{RETS4R is a native Ruby interface to the RETS (Real Estate Transaction Standard)}
  s.test_files = [
    "spec/rets4r_compact_data_parser_spec.rb",
     "test/test_auth.rb",
     "test/test_client.rb",
     "test/test_client_links.rb",
     "test/test_compact_nokogiri.rb",
     "test/test_helper.rb",
     "test/test_listing_mapper.rb",
     "test/test_loader.rb",
     "test/test_parser.rb",
     "test/test_quality.rb",
     "examples/client_get_object.rb",
     "examples/client_login.rb",
     "examples/client_mapper.rb",
     "examples/client_metadata.rb",
     "examples/client_parser.rb",
     "examples/client_search.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.4.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.4.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

