on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         # ruby-version: ['1.9.3', '2.0.0', '2.1.2']
         ruby-version: ['1.9', '2.0', '2.1']
        # TODO: update to non-EOL ruby-version: ['3.1', '3.2', '3.3', '3.4']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: bundle exec rake
